version: '3.7'

services:
  forms-flow-submission-db:
    image: postgres:11
    environment:
      POSTGRES_USER: ${SUBMISSION_API_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${SUBMISSION_API_DB_PASSWORD:-changeme}
      POSTGRES_DB: ${SUBMISSION_API_DB_NAME:-submissionapi}
    ports:
      - '6010:5432'
    restart: unless-stopped
    volumes:
      - ./postgres/submissionapi:/var/lib/postgresql/data
    networks:
      - forms-flow-submission-network

  forms-flow-submission:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - forms-flow-submission-db
    ports:
      - '6212:5000'
    volumes:
      - ./:/app:rw
    environment:
      INSIGHT_API_KEY: ${INSIGHT_API_KEY}
      INSIGHT_API_URL: ${INSIGHT_API_URL}
      DATABASE_URL: ${SUBMISSION_API_DB_URL:-postgresql://postgres:changeme@forms-flow-submission-db:5432/submissionapi}
      BPM_TOKEN_API: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/protocol/openid-connect/token
      BPM_CLIENT_ID: ${KEYCLOAK_BPM_CLIENT_ID:-forms-flow-bpm}
      BPM_CLIENT_SECRET: ${KEYCLOAK_BPM_CLIENT_SECRET:-e4bdbd25-1467-4f7f-b993-bc4b1944c943}
      BPM_API_BASE: ${CAMUNDA_API_URL}
      SUBMISSION_API_CORS_ORIGINS: ${SUBMISSION_API_CORS_ORIGINS:-*}
      JWT_OIDC_WELL_KNOWN_CONFIG: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/.well-known/openid-configuration
      JWT_OIDC_JWKS_URI: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/protocol/openid-connect/certs
      JWT_OIDC_ISSUER: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}
      JWT_OIDC_AUDIENCE: ${KEYCLOAK_WEB_CLIENT_ID:-forms-flow-web}
      JWT_OIDC_CACHING_ENABLED: 'True'
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_URL_REALM: ${KEYCLOAK_URL_REALM:-forms-flow-ai}
      WEB_API_BASE_URL: ${SUBMISSION_API_URL}
    stdin_open: true # -i
    tty: true # -t
    networks:
      - forms-flow-submission-network

networks:
  forms-flow-submission-network:
    driver: 'bridge'

volumes:
  mdb-data:
