"""empty message

Revision ID: 92cdef9b803e
Revises: 3e6133cdb978
Create Date: 2022-07-12 15:09:18.169403

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '92cdef9b803e'
down_revision = '3e6133cdb978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('submission', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('submission', sa.Column('form_id', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'form_id')
    op.drop_column('submission', 'modified')
    op.drop_column('submission', 'created')
    # ### end Alembic commands ###
